Add support for PlaybackUrl in VideoUploadResult
cloudinary/CloudinaryDotNet pull request #338
Opened 2023-10-09 13:23 UTC by Suraj3240

### Brief Summary of Changes
Add support for PlaybackUrl in VideoUploadResult #337

#### What does this PR address?
- [ ] GitHub issue (Add reference - #XX)
- [ ] Refactoring
- [x] New feature
- [ ] Bug fix
- [ ] Adds more tests

#### Are tests included?
- [ ] Yes
- [x] No

#### Reviewer, please note:

#### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I ran the full test suite before pushing the changes and all the tests pass.

2023-10-09 13:58 UTC, Suraj3240 commented
@const-cloudinary

2023-10-09 14:53 UTC, const-cloudinary requested changes
Please fix a small bug

2023-10-09 14:53 UTC, const-cloudinary commented on CloudinaryDotNet.IntegrationTests/UploadApi/UploadMethodsTest.cs
> +            Assert.IsFalse(string.IsNullOrEmpty(updateResult.PlaybackUrl));
```suggestion
            Assert.IsFalse(string.IsNullOrEmpty(uploadResult.PlaybackUrl));
```

2023-10-09 21:27 UTC, merged

2023-10-09 21:29 UTC, const-cloudinary commented
@Suraj3240 thank you for contribution!

2023-10-10 14:17 UTC, Suraj3240 commented
@const-cloudinary can you please add the `hacktobefest` label to this

2023-10-10 14:38 UTC, colbyfayock commented
hey @Suraj3240 label for the PR aside, the repo has the label so it should qualify for your Hacktoberfest.com contribution

<img width="369" alt="image" src="https://github.com/cloudinary/CloudinaryDotNet/assets/1045274/730a9302-55e7-4b0c-83db-bede192d8c57">

2023-10-10 14:53 UTC, Suraj3240 commented
> hey @Suraj3240 label for the PR aside, the repo has the label so it should qualify for your Hacktoberfest.com contribution
> 
> <img alt="image" width="369" src="https://user-images.githubusercontent.com/1045274/273955565-730a9302-55e7-4b0c-83db-bede192d8c57.png">

Ok great. Thank You :))